name: Custom checkout private repository
description: Custom checkout private repository

inputs:
  repo_name:
    description: The repo name
    required: true
  ssh_key:
    description: the private ssh key
    required: true
  known_hosts:
    description: the private ssh key
    required: true  

runs:
  # allow you to bundle multiple workflow steps into a single action, combining multiple run commands into a single reusable action.
  using: "composite"
  steps: 

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ inputs.ssh_key }}
        name: id_rsa
        known_hosts: ${{ inputs.known_hosts }}
        if_key_exists: ignore 
          
    - name: Clone repository
      shell: bash
      env:
       repo: ${{ inputs.repo_name}}
      run: git clone git@github.com:deplotrain/$repo
