name: Custom checkout private repository
description: Custom checkout private repository

inputs:
  repo_name:
    description: The repo name
    required: true
  ssh_key:
    description: the private ssh key
    required: true
  known_hosts:
    description: the private ssh key
    required: true  

runs:
  # allow you to bundle multiple workflow steps into a single action, combining multiple run commands into a single reusable action.
  using: "composite"
  steps: 

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ inputs.ssh_key }}
          
    - name: Clone repository
      shell: bash
      env:
       repo: ${{ inputs.repo_name}}
      run: 
        git clone git@github.com:deplotrain/$repo
