name: "Fetch dependencies across Elixir and Nodejs"
description:  setup ssh-agent to use the private ssh-key to fetch private dependencies

#inputs:
#  mode:
#    description: fetch mode prod or dev
runs:
  using: "composite"
  steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: id_rsa
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name:  fetch elixir dependencies
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{inputs.otp}}
        elixir-version: ${{inputs.elixir}}

    - name: Install hex and rebar
      run: | 
        mix local.hex --force 
        mix local.rebar --force
        mix hex.audit
      if: always()

    - name: Install dependencies
      run: |
        mix deps.audit
        mix deps.get
      if: always()

    - name: Code linting
      run: |
        mix format --check-formatted
        mix credo --strict
        mix sobelow --config
      if: always()

    - name: Run tests
      run: mix test
      if: always()
