name: "Build and Publish Image to Registy"
description: It's build tag , scan before publish the image on registry

inputs:
  url:
    description: "the registry url"
    required: true
  username:
    description: "Username for image registry"
    required: true
  password:
    description: "Password for image registry"
    required: true
  ssh_key:
    description: "ssh private key"
    required: true
  repository:
    description: "Name of the repository on the registry"
    required: true
  tag:
    description: "How to tag the image"
    required: true

runs:
  # allow you to bundle multiple workflow steps into a single action, combining multiple run commands into a single reusable action.
  using: "composite"
  steps:
    - name: Connect to the registry
      uses: docker/login-action@v2
      env: 
        IMAGE_FOR_REGISTRY: ${{ inputs.url }}/${{ inputs.repository }}:${{ inputs.tag }}
        SSH_KEY: ${{ inputs.ssh_key }} 
      with:
        registry: ${{ inputs.url }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Build image with tag
      shell: bash
      run: 
        echo $SSH_KEY
        docker build  --build-arg SSH_KEY=$(echo $SSH_KEY | base64) -t $IMAGE_FOR_REGISTRY . 

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ inputs.url }}/${{ inputs.repository }}:${{ inputs.tag }}
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
#        severity: 'CRITICAL,HIGH'

    - name: Publish image built and scanned to the registry
      shell: bash
      run: docker push $IMAGE_FOR_REGISTRY
