# This is a basic workflow to help you get started with Actions

name: Basic-node-app

  # Triggers the workflow on push or pull request events but only for the "main" branch
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      # Runs a single command using the runners shell
      - name: Try my self-hosted-runner
        run: | 
          docker run hello-world
          
      
      

      

