node_version:=$(shell node -v)
npm_version:=$(shell npm -v)
VERSION ?= ""
COMMIT ?= $(shell git log -1 --format=%h)
BRANCH = $(shell  echo ${GITHUB_REF#refs/heads/})
TIMESTAMP ?= ""



run:
   @echo "it's seem working"
   @echo BRANCH