name: Called Workflow
on:
  workflow_call:
    inputs:
      current_branch:
        required: true
        type: string
jobs:
   TestAndBuildArtifact:
     name: Test and build the artifact
     runs-on: self-hosted
     permissions:
       id-token: write
       contents: read
     steps:
       - uses: actions/checkout@v3
       - uses: ./.github/actions/container-image.yaml@main
       - name: build artifact
         run: |
           mix compile
           mix release
#       - name: Upload artifact
#         uses: actions/upload-artifact@v3
#         with:
#            name: artifact upload
#            path:

   BuildScanAndPublish:
     name: Build Scan and Publish the image
#     needs: TestAndBuildArtifact
     runs-on: self-hosted
     if: ${{inputs.current_branch}} != 'refs/heads/feature**' && contains(join(needs.TestAndBuildArtifact.result, ','), 'success')
     permissions:
       id-token: write
       contents: read
     steps:
       - uses: actions/checkout@v3
       - uses: ./.github/actions/linter.yaml@main
         with:
           url: registry.hub.docker.com
           username: ${{secrets.USERNAME}}
           password: ${{secrets.PASSWORD}}
           repository: hub-covid
           tag: devtag






          
      
      

      

