name: Called Workflow
on:
  workflow_call:
    inputs:
      current_branch:
        required: true
        type: string
      repository:
        required: true
        type: string
      appName:
        required: true
        type: string
    secrets:
      USERNAME: 
        required: true
      PASSWORD: 
        required: true
      SSH_KEY: 
        required: true
      KNOWN_HOSTS: 
        required: true
      S3_BUCKET: 
        required: true
jobs:
  #  TestAndBuildArtifact:
  #    name: Test and build the artifact
  #    runs-on: ubuntu-latest
  #    permissions:
  #      id-token: write
  #      contents: read
  #    steps:
  #      - uses: actions/checkout@v3
       
  #      - uses: deplotrain/.github/.github/actions/linter@main
  #        with:
  #         ssh_key: ${{ secrets.SSH_KEY }}
  #         known_hosts: ${{ secrets.KNOWN_HOSTS }}
          
  #      - name: build artifact
  #        run: |
  #          mix compile
  #          mix release
  #  BuildScanAndPublish:
  #    name: Build Scan and Publish the image
  #    needs: TestAndBuildArtifact
  #    if: ${{ inputs.current_branch }} != 'refs/heads/feature**' && contains(join(needs.TestAndBuildArtifact.result, ','), 'success')
  #    runs-on: ubuntu-latest
  #    permissions:
  #      id-token: write
  #      contents: read
  #    steps:
  #      - uses: actions/checkout@v3
  #      - uses: deplotrain/.github/.github/actions/push-registry@main
  #        with:
  #          url: registry.hub.docker.com
  #          username: ${{ secrets.USERNAME }}
  #          password: ${{ secrets.PASSWORD }}
  #          ssh_key: ${{ secrets.SSH_KEY }}
  #          repository: kueter/hub-covid
  #          tag: devtag
   
   ReleaseHelm: 
      name: Create the release chart helm and push in s3
      runs-on: ubuntu-latest  
      permissions:
        id-token: write
        contents: read
      steps:
   
        - uses: deplotrain/.github/.github/actions/custom-checkout@main
          with: 
            repo_name: ${{ inputs.repository }}
            ssh_key: ${{ secrets.SSH_KEY }}
            

        - uses: deplotrain/.github/.github/actions/release-helm@main
          with:
            url: ${{ secrets.S3_BUCKET }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            imageRef: kueter/hub-covid:devtag
            app: ${{ inputs.appName}}


          
      
      

      

