name: Called Workflow
on:
  workflow_call:
    inputs:
      current_branch:
        required: true
        type: string
    secrets:
      USERNAME: 
        required: true
      PASSWORD: 
        required: true
      SSH_KEY: 
        required: true
      KNOWN_HOSTS: 
        required: true
jobs:

   BuildScanAndPublish:
     name: Build Scan and Publish the image
     runs-on: ubuntu-latest
     permissions:
       id-token: write
       contents: read
     steps:
       - uses: actions/checkout@v3
       - uses: deplotrain/.github/.github/actions/push-registry@main
         with:
           url: registry.hub.docker.com
           username: ${{ secrets.USERNAME }}
           password: ${{ secrets.PASSWORD }}
           ssh_key: ${{ secrets.SSH_KEY }}
           repository: kueter/hub-covid
           tag: devtag






          
      
      

      

